"use client"
import './globals.css'
import 'tailwindcss/tailwind.css'
import { AuthProvider } from '@/contexts/AuthContext'
import { ChakraProvider } from "@chakra-ui/react"
import Head from 'next/head'

export const metadata = {
  title: 'Zuvia Academy',
  description: 'Generated by create next app',
} 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <head> 
        <title> Zuvia Academy | Mundo Cripto & Web3 para todos. </title>
      </head>
      <body>
        <ChakraProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ChakraProvider>
      </body>
    </html>
    </>
  )
}
