import './globals.css'
import { Inter } from 'next/font/google'
import 'tailwindcss/tailwind.css'
import { AuthProvider } from '@/contexts/AuthContext'

export const metadata = {
  title: 'Zuvia Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
